repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: fix-encoding-pragma
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
      - id: autopep8
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
